ci/build: tidy up build-logic (see desc)
- make 'build' task depend on 'javadoc' to ensure we don't break javadocs in the future
- replace 'writeVersionToFile' task with cli command
- simplify processResources
- remove AbstractArchiveTask config (gradle 9 generates reproducible builds by default)
- clean up license handling
- remove 'STABLE_CONFIGURATION_CACHE' feature preview

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -67,12 +67,13 @@ jobs:
       - name: "Read Version"
         if: github.event_name == 'workflow_dispatch'
         run: |
-          ./gradlew writeVersionToFile
-          if [[ ! -f .version || ! -s .version ]]; then
-            echo "Error: .version file is missing or empty."
+          set -e
+          RELEASE_VERSION=$(./gradlew properties --full-stacktrace | grep "version:" | awk '{print $2}')
+          if [[ -z "$RELEASE_VERSION" ]]; then
+            echo "Error: unable to parse version from gradle properties."
             exit 1
           fi
-          echo "RELEASE_VERSION=$(cat .version)" >> $GITHUB_ENV
+          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
 
       - name: "Create GitHub Release"
         if: github.event_name == 'workflow_dispatch' && !contains(env.RELEASE_VERSION, '-')
